// Package auth nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/pokt-network/posmint/x/auth/types
package auth

import (
	"github.com/pokt-network/posmint/x/auth/exported"
	"github.com/pokt-network/posmint/x/auth/types"
)

// Const Constants
const (
	ModuleName        = types.ModuleName
	StoreKey          = types.StoreKey
	FeeCollectorName  = types.FeeCollectorName
	QuerierRoute      = types.QuerierRoute
	DefaultParamspace = types.DefaultParamspace
	QueryAccount      = types.QueryAccount
)

var (
	ProtoBaseAccount          = types.ProtoBaseAccount
	NewBaseAccountWithAddress = types.NewBaseAccountWithAddress
	RegisterCodec             = types.RegisterCodec
	NewGenesisState           = types.NewGenesisState
	DefaultGenesisState       = types.DefaultGenesisState
	CountSubKeys              = types.CountSubKeys
	StdSignBytes              = types.StdSignBytes
	DefaultTxDecoder          = types.DefaultTxDecoder
	DefaultTxEncoder          = types.DefaultTxEncoder
	NewTxBuilder              = types.NewTxBuilder
	NewAccountRetriever       = types.NewAccountRetriever
	ModuleCdc                 = types.ModuleCdc
)

// Type exported types
type (
	Account            = exported.Account
	BaseAccount        = types.BaseAccount
	GenesisState       = types.GenesisState
	Params             = types.Params
	QueryAccountParams = types.QueryAccountParams
	StdTx              = types.StdTx
	StdSignDoc         = types.StdSignDoc
	StdSignature       = types.StdSignature
	TxBuilder          = types.TxBuilder
)
