// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/pokt-network/posmint/x/staking/keeper
// ALIASGEN: github.com/pokt-network/posmint/x/staking/types
// ALIASGEN: github.com/pokt-network/posmint/x/staking/exported
package staking

import (
	"github.com/pokt-network/posmint/x/pos/exported"
	"github.com/pokt-network/posmint/x/pos/keeper"
	"github.com/pokt-network/posmint/x/pos/types"
)

const (
	DefaultParamspace    = keeper.DefaultParamspace
	DefaultCodespace     = types.DefaultCodespace
	CodeInvalidValidator = types.CodeInvalidValidator
	CodeInvalidInput     = types.CodeInvalidInput
	CodeValidatorJailed  = types.CodeValidatorJailed
	CodeInvalidAddress   = types.CodeInvalidAddress
	CodeUnauthorized     = types.CodeUnauthorized
	CodeInternal         = types.CodeInternal
	CodeUnknownRequest   = types.CodeUnknownRequest
	ModuleName           = types.ModuleName
	StoreKey             = types.StoreKey
	QuerierRoute         = types.QuerierRoute
	RouterKey            = types.RouterKey
	DefaultUnstakingTime = types.DefaultUnstakingTime
	DefaultMaxValidators = types.DefaultMaxValidators
	BondedPoolName       = types.StakedPoolName
	QueryValidators      = types.QueryValidators
	QueryValidator       = types.QueryValidator
	QueryPool            = types.QueryPool
	QueryParameters      = types.QueryParameters
)

var (
	// functions aliases
	RegisterInvariants                 = keeper.RegisterInvariants
	AllInvariants                      = keeper.AllInvariants
	ModuleAccountInvariants            = keeper.ModuleAccountInvariants
	NonNegativePowerInvariant          = keeper.NonNegativePowerInvariant
	NewKeeper                          = keeper.NewKeeper
	ParamKeyTable                      = keeper.ParamKeyTable
	NewQuerier                         = keeper.NewQuerier
	RegisterCodec                      = types.RegisterCodec
	ErrNilValidatorAddr                = types.ErrNilValidatorAddr
	ErrBadValidatorAddr                = types.ErrBadValidatorAddr
	ErrNoValidatorFound                = types.ErrNoValidatorFound
	ErrValidatorOwnerExists            = types.ErrValidatorOwnerExists
	ErrValidatorPubKeyExists           = types.ErrValidatorPubKeyExists
	ErrValidatorPubKeyTypeNotSupported = types.ErrValidatorPubKeyTypeNotSupported
	ErrValidatorJailed                 = types.ErrValidatorJailed
	ErrBadRemoveValidator              = types.ErrBadRemoveValidator
	ErrDescriptionLength               = types.ErrDescriptionLength
	ErrCommissionNegative              = types.ErrCommissionNegative
	ErrCommissionHuge                  = types.ErrCommissionHuge
	ErrCommissionGTMaxRate             = types.ErrCommissionGTMaxRate
	ErrCommissionUpdateTime            = types.ErrCommissionUpdateTime
	ErrCommissionChangeRateNegative    = types.ErrCommissionChangeRateNegative
	ErrCommissionChangeRateGTMaxRate   = types.ErrCommissionChangeRateGTMaxRate
	ErrCommissionGTMaxChangeRate       = types.ErrCommissionGTMaxChangeRate
	ErrSelfDelegationBelowMinimum      = types.ErrSelfDelegationBelowMinimum
	ErrMinSelfDelegationInvalid        = types.ErrMinSelfDelegationInvalid
	ErrMinSelfDelegationDecreased      = types.ErrMinSelfDelegationDecreased
	ErrNilDelegatorAddr                = types.ErrNilDelegatorAddr
	ErrBadDenom                        = types.ErrBadDenom
	ErrBadDelegationAddr               = types.ErrBadDelegationAddr
	ErrBadDelegationAmount             = types.ErrBadDelegationAmount
	ErrNoDelegation                    = types.ErrNoDelegation
	ErrBadDelegatorAddr                = types.ErrBadDelegatorAddr
	ErrNoDelegatorForAddress           = types.ErrNoDelegatorForAddress
	ErrInsufficientShares              = types.ErrInsufficientShares
	ErrDelegationValidatorEmpty        = types.ErrDelegationValidatorEmpty
	ErrNotEnoughDelegationShares       = types.ErrNotEnoughDelegationShares
	ErrBadSharesAmount                 = types.ErrBadSharesAmount
	ErrBadSharesPercent                = types.ErrBadSharesPercent
	ErrNotMature                       = types.ErrNotMature
	ErrNoUnbondingDelegation           = types.ErrNoUnstakingDelegation
	ErrMaxUnbondingDelegationEntries   = types.ErrMaxUnstakingDelegationEntries
	ErrBadRedelegationAddr             = types.ErrBadRedelegationAddr
	ErrNoRedelegation                  = types.ErrNoRedelegation
	ErrSelfRedelegation                = types.ErrSelfRedelegation
	ErrVerySmallRedelegation           = types.ErrVerySmallRedelegation
	ErrBadRedelegationDst              = types.ErrBadRedelegationDst
	ErrTransitiveRedelegation          = types.ErrTransitiveRedelegation
	ErrMaxRedelegationEntries          = types.ErrMaxRedelegationEntries
	ErrDelegatorShareExRateInvalid     = types.ErrDelegatorShareExRateInvalid
	ErrBothShareMsgsGiven              = types.ErrBothShareMsgsGiven
	ErrNeitherShareMsgsGiven           = types.ErrNeitherShareMsgsGiven
	ErrMissingSignature                = types.ErrMissingSignature
	NewGenesisState                    = types.NewGenesisState
	DefaultGenesisState                = types.DefaultGenesisState
	NewMultiStakingHooks               = types.NewMultiStakingHooks
	GetValidatorKey                    = types.KeyForValByAllVals
	GetValidatorByConsAddrKey          = types.KeyForValidatorByConsAddr
	AddressFromPrevStateValidatorPowerKey   = types.AddressFromPrevStateValidatorPowerKey
	GetValidatorsByPowerIndexKey       = types.KeyForValidatorInStakingSet
	GetPrevStateValidatorPowerKey           = types.KeyForValidatorPrevStateStateByPower
	ParseValidatorPowerRankKey         = types.ParseValidatorPowerRankKey
	NewMsgCreateValidator              = types.NewMsgStake
	DefaultParams                      = types.DefaultParams
	MustUnmarshalParams                = types.MustUnmarshalParams
	UnmarshalParams                    = types.UnmarshalParams
	NewPool                            = types.NewPool
	NewQueryValidatorParams            = types.NewQueryValidatorParams
	NewQueryValidatorsParams           = types.NewQueryValidatorsParams
	NewValidator                       = types.NewValidator
	MustMarshalValidator               = types.MustMarshalValidator
	MustUnmarshalValidator             = types.MustUnmarshalValidator
	UnmarshalValidator                 = types.UnmarshalValidator

	// variable aliases
	ModuleCdc                 = types.ModuleCdc
	PrevStateValidatorPowerKey     = types.PrevStateValidatorsPowerKey
	PrevStateTotalPowerKey         = types.PrevStateTotalPowerKey
	ValidatorsKey             = types.AllValidatorsKey
	ValidatorsByConsAddrKey   = types.AllValidatorsByConsensusAddrKey
	ValidatorsByPowerIndexKey = types.StakedValidatorsKey
	KeyUnbondingTime          = types.KeyUnstakingTime
	KeyMaxValidators          = types.KeyMaxValidators
	KeyBondDenom              = types.KeyStakeDenom
)

type (
	Keeper                = keeper.Keeper
	CodeType              = types.CodeType
	GenesisState          = types.GenesisState
	PrevStateValidatorPower    = types.PrevStateBlockValidatorPower
	MultiStakingHooks     = types.MultiPOSHooks
	MsgCreateValidator    = types.MsgStake
	Params                = types.Params
	Pool                  = types.StakingPool
	QueryValidatorParams  = types.QueryValidatorParams
	QueryValidatorsParams = types.QueryValidatorsParams
	Validator             = types.Validator
	Validators            = types.Validators
	ValidatorI            = exported.ValidatorI
)
